#Aluno: MACIEL ALVES PEREIRA
n1 = float(input("Digite um número: "))
n2 = float(input("Digite outro número: "))
print(f'A soma dos números é {n1 + n2}')
print(f'A concatenação das strinds: {n1}{int(n2)}')
print(f'A multiplicação dos números é {n1 * n2}')
print(f'Multiplicação como string: {str(n1) * int(n2)}')
print(f'A divisão dos números é {n1 / n2}')
print(f'A divisão inteira dos números é {n1 // n2}')
print(f'Exponenciação de {n1}^{n2} é {n1 ** n2}')
print(f'O resto da divisão ineira é {n1 % n2}')